[package]
name = "pretty_rdf"
version = "0.1.0"
authors = ["Phillip Lord"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.6.1"
quick-xml = "0.21"
rio_api= "0.5.2"

[dev-dependencies]
pretty_assertions = "0.6.1"
rio_turtle = "0.5.2"